<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-LSUVMN2" name="AutomationExModule.AutomationExFeature.AutomationPassScript" tests="7" failures="0" timestamp="13 Nov 2019 10:33:49 GMT" time="42.909" errors="1">
  <testcase name="step_0" time="15.591" classname="AutomationExModule.AutomationExFeature.AutomationPassScript"/>
  <testcase name="step_1" time="4.085" classname="AutomationExModule.AutomationExFeature.AutomationPassScript"/>
  <testcase name="step_2" time="3.923" classname="AutomationExModule.AutomationExFeature.AutomationPassScript"/>
  <testcase name="step_5" time="3.576" classname="AutomationExModule.AutomationExFeature.AutomationPassScript"/>
  <testcase name="step_6" time="3.173" classname="AutomationExModule.AutomationExFeature.AutomationPassScript">
    <error type="java.lang.AssertionError" message="The following asserts failed:
null">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
null
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:37)
	at reuseablePackage.feature.AllActions.AssertAll(AllActions.java:1339)
	at AutomationExModule.AutomationExFeature.AutomationPassScript.step_6(AutomationPassScript.java:228)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- step_6 -->
  <testcase name="step_3" time="2.135" classname="AutomationExModule.AutomationExFeature.AutomationPassScript"/>
  <testcase name="step_4" time="10.426" classname="AutomationExModule.AutomationExFeature.AutomationPassScript"/>
</testsuite> <!-- AutomationExModule.AutomationExFeature.AutomationPassScript -->
